package sashimi

import (
	. "github.com/ionous/sashimi/script"
	"github.com/stretchr/testify/assert"
	"os"
	"testing"
)

// 1. create a simple table declaration and generate some fixed instances
// 2. create a simple table declaration with autogenerated instances
// 3. merge some non-contrary instance data
// 4. test table declarations which use pointers
func TestTableDecl(t *testing.T) {
	s := Script{}
	s.The("kinds",
		Called("sweets"),
		Have("desc", "text"),
		AreOneOf("delicious", "decent", "acceptable", "you can't be serious"))
	s.The("sweet",
		Table("name", "desc", "delicious-property").Contains(
			"boreo", "creme filled wafer things.", "acceptable").And(
			"uncle eddie's vegan chocolate chip", "the name says it all.", "delicious").And(
			"sugar coated ants", "ants. coated with sugar.", "you can't be serious",
		),
	)

	if m, err := s.Compile(os.Stderr); assert.NoError(t, err, "table compile") {
		assert.Len(t, m.Instances, 3)
	}
}
