package source

//
// Rule definitions controlling which values a property can take
//
type RuleType string

const (
	UsuallyExpect RuleType = "usually"
	AlwaysExpect           = "always"
	SeldomExpect           = "seldom"
	NeverExpect            = "never"
)

//
// Generated by the public records.
//
type PropertyExpectation struct {
	rule  RuleType    // style of rule
	value interface{} // expects numbers to be marshelled to float32 in advance
}

func NewExpectation(rule RuleType, value interface{}) PropertyExpectation {
	return PropertyExpectation{rule, value}
}

func (ts PropertyExpectation) RuleType() RuleType {
	return ts.rule
}

func (ts PropertyExpectation) RuleValue() interface{} {
	return ts.value
}
