package source

import (
	. "github.com/ionous/sashimi/source/types"
)

// r/o container for an array of column data
// ( not completely true because the values aren't copied.)
type MultiValueStatement struct {
	fields MultiValueFields
	source Code
}

// MultiValueFields contains a row of column data for an instance.
// When Owner refers to a class, a new instance will be generated by the compiler.
// The column containing "name" designates the name of the instance.
// If no such column exists, a name will be automatically generated by the compiler.
type MultiValueFields struct {
	Owner   string // class or instance
	Columns []string
	Rows    []Row
}

type Row []interface{}

//
func (ts MultiValueStatement) Fields() MultiValueFields {
	return ts.fields
}

func (ts MultiValueStatement) Source() Code {
	return ts.source
}
